DROP TABLE IF EXISTS user_account;
CREATE TABLE user_account (ACCOUNT_ID LONG PRIMARY KEY AUTO_INCREMENT NOT NULL, USER_NAME VARCHAR(50), CURRENCY_CODE VARCHAR(10), BALANCE_AMOUNT DECIMAL(15,4) );
CREATE UNIQUE INDEX ac_idx on user_account(USER_NAME,CURRENCY_CODE);

INSERT INTO user_account (USER_NAME, CURRENCY_CODE, BALANCE_AMOUNT) VALUES ('JOHN','USD', 1000.0000);
INSERT INTO user_account (USER_NAME, CURRENCY_CODE, BALANCE_AMOUNT) VALUES ('MERRY','USD', 2000.0000);
INSERT INTO user_account (USER_NAME, CURRENCY_CODE, BALANCE_AMOUNT) VALUES ('LUCY','EUR', 3000.0000);
INSERT INTO user_account (USER_NAME, CURRENCY_CODE, BALANCE_AMOUNT) VALUES ('ROSE','EUR', 4000.0000);
INSERT INTO user_account (USER_NAME, CURRENCY_CODE, BALANCE_AMOUNT) VALUES ('HAPPY','GBP', 5000.0000);
INSERT INTO user_account (USER_NAME, CURRENCY_CODE, BALANCE_AMOUNT) VALUES ('TAYLOR','GBP', 6000.0000);
INSERT INTO user_account (USER_NAME, CURRENCY_CODE, BALANCE_AMOUNT) VALUES ('PONTING','USD', 7000.0000);
INSERT INTO user_account (USER_NAME, CURRENCY_CODE, BALANCE_AMOUNT) VALUES ('PELLE','USD', 8000.0000);


DROP TABLE IF EXISTS user;
CREATE TABLE user (USER_ID LONG PRIMARY KEY AUTO_INCREMENT NOT NULL, NAME VARCHAR(50) NOT NULL, EMAIL_ID VARCHAR(50) NOT NULL);
CREATE UNIQUE INDEX usr_idx on user(NAME, EMAIL_ID);

INSERT INTO user (NAME, EMAIL_ID) VALUES ('JOHN','john123@gmail.com');
INSERT INTO user (NAME, EMAIL_ID) VALUES ('MERRY','merry654@gmail.com');
INSERT INTO user (NAME, EMAIL_ID) VALUES ('LUCY','lucy369@gmail.com');
INSERT INTO user (NAME, EMAIL_ID) VALUES ('ROSE','rose123@gmail.com');
INSERT INTO user (NAME, EMAIL_ID) VALUES ('TAYLOR','taylor654@gmail.com');
INSERT INTO user (NAME, EMAIL_ID) VALUES ('PONTING','ponting001@gmail.com');
INSERT INTO user (NAME, EMAIL_ID) VALUES ('PELLE','pelle369@gmail.com');